Adjust Donates from users page on manager portal
MimirLibrary/mimir pull request #545
Opened 2022-12-30 14:40 UTC by IAlexHilimovich

Closes #536

2023-01-18 12:05 UTC, Chichmarin17 requested changes
Таблица не очень отображается на планшете, попробуй в react-response прокинуть не phone-width, а tablet-width
![image](https://user-images.githubusercontent.com/73520274/213167016-848e0235-2a62-4c37-a948-52131079556b.png)

2023-01-18 12:05 UTC, Chichmarin17 commented on packages/frontapp/src/app/components/OneDonatedBookPreview/CardSection.tsx
> +const cardSectionContainer = css`
Что делает этот StyleComponent? Не видел такой записи до этого. Не добавляет ли он глобальные стили?

2023-01-18 12:05 UTC, Chichmarin17 commented on packages/frontapp/src/app/components/OneDonatedBookPreview/TableRowView.tsx
> +  grayBackground: boolean;
`isBackgroundGray` или посмотреть, почему задний фон серый и добавить соответсвтующий пропс (например isActive было бы лучше)

2023-01-18 12:05 UTC, Chichmarin17 commented on packages/frontapp/src/app/components/OneDonatedBookPreview/TableRowView.tsx
> +  line-height: 17px;
Посмотри, мб есть что-то в ui kit для lineHeight

2023-01-18 12:05 UTC, Chichmarin17 commented on packages/frontapp/src/app/components/OneDonatedBookPreview/TableRowView.tsx
> +  font-size: 14px;
ui kit package, dimensions

2023-01-18 12:05 UTC, Chichmarin17 commented on packages/frontapp/src/app/components/OneDonatedBookPreview/TableRowView.tsx
> +  font-size: 16px;
ui kit

2023-01-18 12:05 UTC, Chichmarin17 commented on packages/frontapp/src/app/components/OneDonatedBookPreview/TableRowView.tsx
> +  font-size: 16px;
ui kit

2023-01-18 12:05 UTC, Chichmarin17 commented on packages/frontapp/src/app/components/OneDonatedBookPreview/TableRowView.tsx
> +    margin-top: 40px;
Попробуй перевести в `rem`

2023-01-18 12:05 UTC, Chichmarin17 commented on packages/frontapp/src/app/components/OneDonatedBookPreview/TableRowView.tsx
> +  padding: 0px 10px;
ui kit

2023-01-18 12:05 UTC, Chichmarin17 commented on packages/frontapp/src/app/components/OneDonatedBookPreview/TableRowView.tsx
> +  gap: 20px;
чекни ui kit

2023-01-18 12:05 UTC, Chichmarin17 commented on packages/frontapp/src/app/components/OneDonatedBookPreview/TableRowView.tsx
> +          <StatusBadge type="danger">Rejected</StatusBadge>
попробуй прокинуть в button перевод (вроде для этого у i18n есть хук, динамически изменять перевод)

2023-01-18 12:05 UTC, Chichmarin17 commented on packages/frontapp/src/app/components/OneDonatedBookPreview/index.tsx
> +    margin-top: 16px;
ui kit

2023-01-18 12:52 UTC, Yoinezero commented
I don't know where this place in code, but some buttons have disappeared here
Donates: 
![image](https://user-images.githubusercontent.com/48247186/213175934-e04375b9-a1eb-437e-829b-4fbf86b09058.png)
Any other page:
![image](https://user-images.githubusercontent.com/48247186/213176220-2c906386-08ba-4c8c-90e9-4d2647088db7.png)
If it is unnecessary then just skip this notice

2023-01-18 13:28 UTC, IAlexHilimovich commented on packages/frontapp/src/app/components/Card/index.tsx
> +});
Это такой паттерн, чтобы не экспортить отдельные компоненты. Потом можно использовать <Card.Img /> компонент и т.д.

2023-01-18 13:30 UTC, IAlexHilimovich commented on packages/frontapp/src/app/components/DonatesFromUserContent/DonatesFromUserContent.tsx
> +      <hr />
Это я вынес из другого компонента. Он вроде марджин задает, если я правильно помню

2023-01-18 13:33 UTC, IAlexHilimovich commented on packages/frontapp/src/app/components/OneDonatedBookPreview/CardSection.tsx
> +const cardSectionContainer = css`
Добавляет класс с соответствующими стилями. Класс должен быть уникальным. Насколько я помню, я его использовал потому что запись `& + & {
    margin-top: 16px;
  }` по другому не работает

2023-01-19 07:16 UTC, Chichmarin17 commented on packages/frontapp/src/app/components/Card/index.tsx
> +});
странно, мы к уже готовой функции добавляем еще поля, которые являются компонентами, то есть Card ответственен и за рендер в себе children, и за отрисовку каждого children как своего свойства

2023-01-19 11:29 UTC, IAlexHilimovich commented on packages/frontapp/src/app/components/Card/index.tsx
> +});
Card не ответственен за рендер children, он просто содержит ссылки на другие компоненты, то есть это namespace для компонентов
Имя можно добавить

2023-01-20 08:15 UTC, Chichmarin17 requested changes
quick fixes required

2023-01-20 08:15 UTC, Chichmarin17 commented on packages/frontapp/src/app/components/OneDonatedBookPreview/CardView.tsx
> +          <Button onClick={() => accept()} value={t('Buttons.Accept')} />
Можно просто передать функцию accept, без доп обертки

2023-01-20 08:15 UTC, Chichmarin17 commented on packages/frontapp/src/app/components/OneDonatedBookPreview/CardView.tsx
> +            onClick={() => reject()}
См выше

2023-01-20 08:15 UTC, Chichmarin17 commented on packages/frontapp/src/app/components/OneDonatedBookPreview/TableRowView.tsx
> +          <Button onClick={() => accept()} value={t('Buttons.Accept')} />
см выше

2023-01-20 08:21 UTC, Chichmarin17 commented
Resolve merge conflicts

2023-01-20 12:08 UTC, Chichmarin17 approved these changes

2023-01-23 09:06 UTC, merged