Draft: Fix: adjust user page on manager portal
MimirLibrary/mimir pull request #546
Opened 2023-01-03 16:42 UTC by Yoinezero

- add dependency `react-responsive`
- create MobileItem component
- attune @media styles for phone size

2023-01-18 11:37 UTC, Chichmarin17 requested changes

2023-01-18 11:37 UTC, Chichmarin17 commented on packages/frontapp/src/app/components/ClaimHistory/index.tsx
> +  } ;
Из-за этих изменений поехали карточки. Убери их - и они опять норм выглядят
![image](https://user-images.githubusercontent.com/73520274/213161592-8f599cd4-c8c4-441b-a201-d8d4814ade79.png)

2023-01-18 11:37 UTC, Chichmarin17 commented on packages/frontapp/src/app/components/ClaimHistory/index.tsx
> +  } ;
При наведении 
![image](https://user-images.githubusercontent.com/73520274/213161822-6cb6bf5e-db82-4d08-a7ad-86a1c8a4ffac.png)

2023-01-18 11:51 UTC, Chichmarin17 commented
Скорее всего тесты, обнови снепшоты

2023-01-18 12:06 UTC, Chichmarin17 approved these changes

2023-01-19 18:40 UTC, ngame2011 approved these changes

2023-01-19 18:42 UTC, merged